version: "3"
services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - "8000:8080"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/sites-available/:/etc/nginx/sites-available/
      # 這裡需要根據實際情況修改
      - /home/sunlong/projects/php/unmanned_shelf:/var/www/unmanned_shelf:ro
      - /home/sunlong/projects/apidocs/unmanned_shelf-doc:/var/www/unmanned_shelf-doc:ro
    networks:
      - app_env

networks:
  app_env:
    external:
      name: app_env
