version: "3"
services:
  nginx:
    image: nginx:1.13-alpine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/sites-available/:/etc/nginx/sites-available/
      #- /home/sunlong/projects/php/unmanned_shelf:/var/www/unmanned_shelf:ro
      - /home/sunlong/projects/php/jiegao:/var/www/jiegao:ro
      #- /home/sunlong/projects/html/forum:/var/www/forum:ro
    networks:
      - app_net
    ports:
      - "8088:8088"

networks:
  app_net:
    external:
      name: app_net
