version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sunlong0717
    volumes:
      - ./conf:/etc/mysql/conf.d
    networks:
      - app_net
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: sunlong0717
    networks:
      - app_net
    ports:
      - "8081:80"

networks:
  app_net:
    external:
      name: app_net