version: "3"
services:
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app_net

  phpredisadmin:
      image: wqer/mini-redisadmin
      container_name: redisAdmin
      environment:
        - ADMIN_USER=admin
        - ADMIN_PASS=admin
        - REDIS_1_HOST=redis
        - REDIS_1_PORT=6379
      networks:
        - app_net
      ports:
        - "8082:80"

networks:
  app_net:
    external:
      name: app_net
